# Tests for scripts/_univ_parse.fish — the parser used by the univ-var
# import sub-pass to read names + values out of an auto-generated
# exported-univ-vars.fish without sourcing it (which would mutate live
# state pre-decision).
#
# Run via `scripts/run-tests` (fishtape).

set -l repo_root (dirname (realpath (status -f)))/..
source $repo_root/scripts/_univ_parse.fish

# ─── Fixture: a realistic export file matching _univ_regenerate's output ─

set -l fixture (mktemp)
echo "# Auto-generated by wrangle. Edit .univexport (allowlist) and re-run wrangle." > $fixture
echo "# Restored automatically by wrangle sync." >> $fixture
echo "" >> $fixture
echo "set -U --erase tide_pwd_color_dirs" >> $fixture
echo "set -U tide_pwd_color_dirs 0087AF" >> $fixture
echo "set -U --erase tide_prompt_chars" >> $fixture
echo "set -U tide_prompt_chars a b c" >> $fixture
echo "set -U --erase sponge_color" >> $fixture
# Realistic escaping: _univ_regenerate runs each value through `string escape`,
# which single-quotes any token containing whitespace.
echo "set -U sponge_color 'has space'" >> $fixture
echo "" >> $fixture

# ─── parse_names: returns every tracked var, skipping --erase lines + comments

set -l names (_wrangle_univ_parse_names $fixture)

@test "parse_names returns 3 tracked vars" (count $names) -eq 3

contains -- tide_pwd_color_dirs $names
@test "parse_names finds tide_pwd_color_dirs" $status -eq 0

contains -- tide_prompt_chars $names
@test "parse_names finds tide_prompt_chars" $status -eq 0

contains -- sponge_color $names
@test "parse_names finds sponge_color" $status -eq 0

# Sanity: --erase lines and comments are NOT returned as names.
not contains -- --erase $names
@test "parse_names does not return --erase as a name" $status -eq 0

# ─── parse_values: single-value var ──────────────────────────────────────

set -l v1 (_wrangle_univ_parse_values $fixture tide_pwd_color_dirs)
@test "parse_values: tide_pwd_color_dirs returns 1 value" (count $v1) -eq 1

test "$v1[1]" = 0087AF
@test "parse_values: tide_pwd_color_dirs value is 0087AF" $status -eq 0

# ─── parse_values: multi-value var ──────────────────────────────────────

set -l v2 (_wrangle_univ_parse_values $fixture tide_prompt_chars)
@test "parse_values: tide_prompt_chars returns 3 values" (count $v2) -eq 3

test "$v2[1]" = a
@test "parse_values: tide_prompt_chars[1] = a" $status -eq 0
test "$v2[2]" = b
@test "parse_values: tide_prompt_chars[2] = b" $status -eq 0
test "$v2[3]" = c
@test "parse_values: tide_prompt_chars[3] = c" $status -eq 0

# ─── parse_values: value containing whitespace (string-escaped in source) ─

set -l v3 (_wrangle_univ_parse_values $fixture sponge_color)
@test "parse_values: sponge_color returns 1 value (escaped whitespace stays one token)" (count $v3) -eq 1

test "$v3[1]" = "has space"
@test "parse_values: sponge_color value unescapes to 'has space'" $status -eq 0

# ─── parse_values: unknown name → empty ─────────────────────────────────

set -l v4 (_wrangle_univ_parse_values $fixture nonexistent_var)
@test "parse_values: unknown var returns empty" (count $v4) -eq 0

# ─── Missing file: both functions return empty without erroring ─────────

set -l missing_names (_wrangle_univ_parse_names /tmp/no-such-file-$fish_pid)
@test "parse_names: missing file returns empty" (count $missing_names) -eq 0

set -l missing_vals (_wrangle_univ_parse_values /tmp/no-such-file-$fish_pid foo)
@test "parse_values: missing file returns empty" (count $missing_vals) -eq 0

# ─── Comments-only file: parse_names returns empty ──────────────────────

set -l empty_fixture (mktemp)
echo "# nothing tracked yet" > $empty_fixture
echo "" >> $empty_fixture
set -l empty_names (_wrangle_univ_parse_names $empty_fixture)
@test "parse_names: comments-only file returns empty" (count $empty_names) -eq 0
rm -f $empty_fixture

rm -f $fixture
