# Parser for the auto-generated exported-univ-vars.fish format. Extracted
# from scripts/wrangle so test/univ-import-parse.fish can source it without
# invoking the rest of wrangle.
#
# The export file is written by _univ_regenerate (scripts/wrangle) and has
# a stable shape: for each tracked universal, two lines —
#     set -U --erase <name>
#     set -U <name> <values...>
# Values are `string escape`'d, so they round-trip through `string unescape`.
# Comments (#) and blank lines are allowed and ignored.
#
# Functions:
#   _wrangle_univ_parse_names <file> → emits one tracked var name per line
#   _wrangle_univ_parse_values <file> <name> → emits the var's unescaped values,
#                                              one per line. Empty output if
#                                              <name> not present.

function _wrangle_univ_parse_names --argument-names file
    test -f $file; or return 0
    # Match `set -U <name> ...` lines, skipping `set -U --erase <name>`.
    # Print the third whitespace-delimited token (the name).
    awk '/^set -U[[:space:]]/ && !/^set -U[[:space:]]+--erase/ {print $3}' $file
end

function _wrangle_univ_parse_values --argument-names file name
    test -f $file; or return 0
    # Find the `set -U <name> ...` line, peel off the `set -U <name> ` prefix
    # to get the (already fish-escaped) value list. Let fish itself tokenize
    # it via `eval` — manual `string split ' '` doesn't respect quote/escape
    # boundaries (a value like `'has space'` would be split mid-token).
    #
    # Trust model: the export file is auto-generated by _univ_regenerate and
    # committed to the repo. The old `wrangle import-univ-vars` literally
    # `source`d this same file, so `eval`-ing one extracted line per call
    # is no broader.
    set -l line (awk -v n=$name '/^set -U[[:space:]]/ && !/^set -U[[:space:]]+--erase/ && $3 == n {print; exit}' $file)
    test -z "$line"; and return 0
    set -l args_line (string replace -r '^set -U[[:space:]]+'$name'[[:space:]]+' '' -- $line)
    test -z "$args_line"; and return 0
    eval "printf '%s\n' $args_line"
end
